### ISSUE TITLE
CartesianError.js not committed 

### ISSUE THREAD

**Issue by saasmath** [kallaspriit/Robocup-Simulator#1]
Note that I am a high-school teacher and we are making a robot simulator for controlling Roomba create robots and I found your very interesting project.

It appears that CartesianError.js was not included in the last commit.  I removed the reference in index.html and Robot.js as it seemed to be used only for diagnostics.  But you may want to commit the file.

Also, it would be great if you could add an MIT or other license of your choice to your work so that we and perhaps others can build and contribute more directly to what seems like a very fine project.

--Gary

**Comment by kallaspriit** [comment]
I added the missing file as well as the MIT licence so feel free to use this in any way you'd like to. I also updated the github webpage with the latest simulator version :)

May I ask what kind of project are you considering using this for?

**Comment by saasmath** [comment]
My class is interested in making a web-based simulator, monitor, and controller for the iRobot Create robots we use.  It was clear when I came across your work that this project could be very useful for what we are doing. Thanks for making this available!

**Comment by kallaspriit** [comment]
Cool, I hope you'll find it useful and let me know if you get anywhere with this :)
